{"name": "Принять заказ без id заказа", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 400)\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test_order_accept.TestOrdersAccept object at 0x000001EE2FD90F10>\ncreate_and_delete_courier = (<Response [201]>, {'login': 'giphpecjpt', 'password': 'xnpwimksdy'}, {'login': 'giphpecjpt', 'password': 'xnpwimksdy'})\n\n    @allure.title('Принять заказ без id заказа')\n    @allure.description('Заказа должна вернуть ошибку 400')\n    def test_accept_order_without_order_id_fail(self, create_and_delete_courier):\n        r = requests.post(TestCourierLinks.login_url, data=create_and_delete_courier[2])\n        courier_id = (r.json()['id'])\n        params = {'courierId': courier_id}\n        response = requests.put(OrdersLinks.accept_order, params=params)\n>       assert response.status_code == 400 and response.json()['message'] == \"Недостаточно данных для поиска\"\nE       assert (404 == 400)\nE        +  where 404 = <Response [404]>.status_code\n\nTests\\test_order_accept.py:55: AssertionError"}, "description": "Заказа должна вернуть ошибку 400", "start": 1701765576078, "stop": 1701765576828, "uuid": "fb1d0df6-a5f9-448f-9ab9-b324e03ee2f9", "historyId": "3e799bd0024ce692092e85f0cced9f2e", "testCaseId": "3e799bd0024ce692092e85f0cced9f2e", "fullName": "Tests.test_order_accept.TestOrdersAccept#test_accept_order_without_order_id_fail", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_order_accept"}, {"name": "subSuite", "value": "TestOrdersAccept"}, {"name": "host", "value": "LAPTOP-EMEFLSN2"}, {"name": "thread", "value": "10136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_order_accept"}]}